# This file defines how gitpod.io should make this project
# available for editing in its browser-based IDE.
# See https://www.gitpod.io/docs/config-gitpod-file

image:
  file: .gitpod.Dockerfile

ports:
  - name: Electric Book server
    description: A web output of your Electric Book project 
    port: 4000

vscode:
  extensions:

    # This extension lets us see live-refreshing PDF outputs
    # in the browser, e.g. during page refinement.
    - yandeu.five-server
