title: "Samples"
subtitle: "Sample content for Electric Book print, epub and web output"
creator: "Arthur Attwell" # E.g. the author
contributor: "" # E.g. other contributors
subject: "Publishing" # E.g. BISAC terms (https://www.bisg.org/bisac/bisac-subject-codes) or BIC (https://ns.editeur.org/bic_categories)
description: >
  Sample content demonstrating Electric Book support for a wide range of book features.
publisher: "Electric Book Works" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2016-09-01" # YYYY-MM-DD e.g. publication date
modified: "2016-09-23" # YYYY-MM-DD e.g. date of last revision
type: "Guide" # e.g. Novel, Poetry, Memoir
identifier: "978-1-928313-13-7" # e.g. ISBN or UUID
source: "978-1-928313-13-7" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "" # who owns the copyright?
rights: "This work is licensed under a [Creative Commons Attribution 4.0 International License](http://creativecommons.org/licenses/by/4.0/). This means you are free to share (copy and redistribute the material in any medium or format) and adapt it (remix, transform, and build upon the material) for any purpose, even commercially, as long as you give appropriate credit, with a link to your source, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use." # e.g. a copyright statement
image: "cover.jpg"

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2016-09-01" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    files:
      - "00-01-halftitle-page"
      - "00-02-previous-publications-page"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "00-06-dedication-page"
      - "00-07-epigraph-page"
      - "00-08-frontispiece-page"
      - "00-09-frontmatter"
      - "01-00-text"
      - "01-01-plain-text"
      - "01-02-headings"
      - "01-03-quotes"
      - "01-04-lists"
      - "01-05-tables"
      - "01-06-boxes"
      - "01-07-notes"
      - "01-08-dividers"
      - "01-09-poetry"
      - "01-10-questions"
      - "02-00-images"
      - "02-01-plain-images"
      - "02-02-figures"
      - "03-00-code-and-maths"
      - "03-01-code"
      - "03-02-maths"
      - "04-00-interactivity"
      - "04-01-links-buttons"
      - "04-02-video"
      - "04-03-audio"
      - "04-04-iframes"
      - "04-05-slides"
      - "10-00-indexes"
      - "10-01-traditional-index"
      - "10-02-dynamic-index"
    toc:
      - label: "Half title page"
        file: "00-01-halftitle-page"
        class: "frontmatter-entry"
      - label: "Previous publications"
        file: "00-02-previous-publications-page"
        class: "frontmatter-entry"
      - label: "Title page"
        file: "00-03-title-page"
        class: "frontmatter-entry"
      - label: "Copyright"
        file: "00-04-copyright-page"
        class: "frontmatter-entry"
      - label: "Contents"
        file: "00-05-contents-page"
        class: "frontmatter-entry"
      - label: "Dedication"
        file: "00-06-dedication-page"
        class: "frontmatter-entry"
      - label: "Epigraph"
        file: "00-07-epigraph-page"
        class: "frontmatter-entry"
      - label: "Frontispiece"
        file: "00-08-frontispiece-page"
        class: "frontmatter-entry"
      - label: "Other frontmatter"
        file: "00-09-frontmatter"
        class: "frontmatter-entry"
      - label: "Text"
        children:
          - label: "Plain text"
            file: "01-01-plain-text"
            id: "plain-text"
          - label: "Headings"
            file: "01-02-headings"
            id: "headings"
          - label: "Quotes"
            file: "01-03-quotes"
            id: "quotes"
            children:
              - label: "Blockquotes"
                file: "01-03-quotes"
                id: "blockquotes"
              - label: "Pullquotes"
                file: "01-03-quotes"
                id: "pullquotes"
              - label: "Quote sources"
                file: "01-03-quotes"
                id: "quote-sources"
          - label: "Lists"
            file: "01-04-lists"
            id: "lists"
            children:
              - label: "Simple lists"
                file: "01-04-lists"
                id: "simple-lists"
              - label: "Chapter tables of contents"
                file: "01-04-lists"
                id: "chapter-contents"
              - label: "Bibliographies"
                file: "01-04-lists"
                id: "bibliographies"
              - label: "Definitions and glossaries"
                file: "01-04-lists"
                id: "definitions-and-glossaries"
          - label: "Tables"
            file: "01-05-tables"
            id: "tables"
          - label: "Boxes"
            file: "01-06-boxes"
            id: "boxes"
          - label: "Notes"
            file: "01-07-notes"
            id: "notes"
          - label: "Dividers"
            file: "01-08-dividers"
            id: "dividers"
          - label: "Poetry"
            file: "01-09-poetry"
            id: "poetry"
          - label: "Questions and quizzes"
            file: "01-10-questions"
            id: "questions-and-quizzes"
      - label: "Images"
        children:
          - label: "Plain images"
            file: "02-01-plain-images"
            id: "plain-images"
          - label: "Figures"
            file: "02-02-figures"
            id: "figures"
      - label: "Code and mathematics"
        children:
          - label: "Code"
            file: "03-01-code"
            id: "code"
          - label: "Mathematics"
            file: "03-02-maths"
            id: "mathematics"
      - label: "Interactivity"
        children:
          - label: "Links and buttons"
            file: "04-01-links-buttons"
            id: "links-and-buttons"
          - label: "Video"
            file: "04-02-video"
            id: "video"
          - label: "Audio"
            file: "04-03-audio"
            id: "audio"
          - label: "iFrames"
            file: "04-04-iframes"
            id: "iframes"
          - label: "Slides"
            file: "04-05-slides"
            id: "slides"
      - label: "Indexes"
        children:
          - label: "Traditional index"
            file: "10-01-traditional-index"
            id: "traditional-index"
          - label: "Dynamic index"
            file: "10-02-dynamic-index"
            id: "dynamic-index"
  web:
    date: "2016-09-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital online" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    files:
      - "index"
      - "00-01-halftitle-page"
      - "00-02-previous-publications-page"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "00-06-dedication-page"
      - "00-07-epigraph-page"
      - "00-08-frontispiece-page"
      - "00-09-frontmatter"
      - "01-00-text"
      - "01-01-plain-text": "Chapter 1"
      - "01-02-headings"
      - "01-03-quotes"
      - "01-04-lists"
      - "01-05-tables"
      - "01-06-boxes"
      - "01-07-notes"
      - "01-08-dividers"
      - "01-09-poetry"
      - "01-10-questions"
      - "02-00-images"
      - "02-01-plain-images"
      - "02-02-figures"
      - "03-00-code-and-maths"
      - "03-01-code"
      - "03-02-maths"
      - "04-00-interactivity"
      - "04-01-links-buttons"
      - "04-02-video"
      - "04-03-audio"
      - "04-04-iframes"
      - "04-05-slides"
      - "10-00-indexes"
      - "10-01-traditional-index"
      - "10-02-dynamic-index"
    nav:
      - label: "Frontmatter"
        class: "cover-entry"
        children:
          - label: "Half title page"
            file: "00-01-halftitle-page"
            class: "frontmatter-entry"
          - label: "Previous publications"
            file: "00-02-previous-publications-page"
            class: "frontmatter-entry"
          - label: "Title page"
            file: "00-03-title-page"
            class: "frontmatter-entry"
          - label: "Copyright"
            file: "00-04-copyright-page"
            class: "frontmatter-entry"
          - label: "Contents"
            file: "00-05-contents-page"
            class: "frontmatter-entry"
          - label: "Dedication"
            file: "00-06-dedication-page"
            class: "frontmatter-entry"
          - label: "Epigraph"
            file: "00-07-epigraph-page"
            class: "frontmatter-entry"
          - label: "Frontispiece"
            file: "00-08-frontispiece-page"
            class: "frontmatter-entry"
          - label: "Other frontmatter"
            file: "00-09-frontmatter"
            class: "frontmatter-entry"
      - label: "Text"
        children:
          - label: "Plain text"
            file: "01-01-plain-text"
            id: "plain-text"
          - label: "Headings"
            file: "01-02-headings"
            id: "headings"
          - label: "Quotes"
            file: "01-03-quotes"
            id: "quotes"
            children:
              - label: "Blockquotes"
                file: "01-03-quotes"
                id: "blockquotes"
              - label: "Pullquotes"
                file: "01-03-quotes"
                id: "pullquotes"
              - label: "Quote sources"
                file: "01-03-quotes"
                id: "quote-sources"
          - label: "Lists"
            file: "01-04-lists"
            id: "lists"
            children:
              - label: "Simple lists"
                file: "01-04-lists"
                id: "simple-lists"
              - label: "Chapter tables of contents"
                file: "01-04-lists"
                id: "chapter-contents"
              - label: "Bibliographies"
                file: "01-04-lists"
                id: "bibliographies"
              - label: "Definitions and glossaries"
                file: "01-04-lists"
                id: "definitions-and-glossaries"
          - label: "Tables"
            file: "01-05-tables"
            id: "tables"
          - label: "Boxes"
            file: "01-06-boxes"
            id: "boxes"
          - label: "Notes"
            file: "01-07-notes"
            id: "notes"
          - label: "Dividers"
            file: "01-08-dividers"
            id: "dividers"
          - label: "Poetry"
            file: "01-09-poetry"
            id: "poetry"
          - label: "Questions and quizzes"
            file: "01-10-questions"
            id: "questions-and-quizzes"
      - label: "Images"
        children:
          - label: "Plain images"
            file: "02-01-plain-images"
            id: "plain-images"
          - label: "Figures"
            file: "02-02-figures"
            id: "figures"
      - label: "Code and mathematics"
        children:
          - label: "Code"
            file: "03-01-code"
            id: "code"
          - label: "Mathematics"
            file: "03-02-maths"
            id: "mathematics"
      - label: "Interactivity"
        children:
          - label: "Links and buttons"
            file: "04-01-links-buttons"
            id: "links-and-buttons"
          - label: "Video"
            file: "04-02-video"
            id: "video"
          - label: "Audio"
            file: "04-03-audio"
            id: "audio"
          - label: "iFrames"
            file: "04-04-iframes"
            id: "iframes"
          - label: "Slides"
            file: "04-05-slides"
            id: "slides"
      - label: "Indexes"
        children:
          - label: "Traditional index"
            file: "10-01-traditional-index"
            id: "traditional-index"
          - label: "Dynamic index"
            file: "10-02-dynamic-index"
            id: "dynamic-index"
    start-page: "00-05-contents-page" # At which file should users start reading?
    contents-page: "00-05-contents-page" # Your contents-page file, if you have one.
  epub:
    date: "2016-09-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "9780000000000" # e.g. ISBN or UUID
    image: "cover.jpg"
    start-page: "00-05-contents-page"
    contents-page: "00-05-contents-page"
    files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
      - "00-00-cover": "cover"
      - "00-01-halftitle-page"
      - "00-02-previous-publications-page"
      - "00-03-title-page": "title-page"
      - "00-04-copyright-page": "copyright-page"
      - "00-05-contents-page": "toc"
      - "00-06-dedication-page": "dedication"
      - "00-07-epigraph-page": "epigraph"
      - "00-08-frontispiece-page"
      - "00-09-frontmatter": "preface"
      - "01-00-text": "text"
      - "01-01-plain-text"
      - "01-02-headings"
      - "01-03-quotes"
      - "01-04-lists"
      - "01-05-tables"
      - "01-06-boxes"
      - "01-07-notes"
      - "01-08-dividers"
      - "01-09-poetry"
      - "01-10-questions"
      - "02-00-images"
      - "02-01-plain-images"
      - "02-02-figures"
      - "03-00-code-and-maths"
      - "03-01-code"
      - "03-02-maths"
      - "04-00-interactivity"
      - "04-01-links-buttons"
      - "04-02-video"
      - "04-03-audio"
      - "04-04-iframes"
      - "04-05-slides"
      - "10-00-indexes"
      - "10-01-traditional-index"
      - "10-02-dynamic-index"
  screen-pdf:
    date: "2016-09-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "00-00-cover"
      - "00-01-halftitle-page"
      - "00-02-previous-publications-page"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "00-06-dedication-page"
      - "00-07-epigraph-page"
      - "00-08-frontispiece-page"
      - "00-09-frontmatter"
      - "01-00-text"
      - "01-01-plain-text"
      - "01-02-headings"
      - "01-03-quotes"
      - "01-04-lists"
      - "01-05-tables"
      - "01-06-boxes"
      - "01-07-notes"
      - "01-08-dividers"
      - "01-09-poetry"
      - "01-10-questions"
      - "02-00-images"
      - "02-01-plain-images"
      - "02-02-figures"
      - "03-00-code-and-maths"
      - "03-01-code"
      - "03-02-maths"
      - "04-00-interactivity"
      - "04-01-links-buttons"
      - "04-02-video"
      - "04-03-audio"
      - "04-04-iframes"
      - "04-05-slides"
      - "10-00-indexes"
      - "10-01-traditional-index"
      - "10-02-dynamic-index"
  app:
    date: "2016-09-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    files:
      - "index"
      - "00-01-halftitle-page"
      - "00-02-previous-publications-page"
      - "00-03-title-page"
      - "00-04-copyright-page"
      - "00-05-contents-page"
      - "00-06-dedication-page"
      - "00-07-epigraph-page"
      - "00-08-frontispiece-page"
      - "00-09-frontmatter"
      - "01-00-text"
      - "01-01-plain-text"
      - "01-02-headings"
      - "01-03-quotes"
      - "01-04-lists"
      - "01-05-tables"
      - "01-06-boxes"
      - "01-07-notes"
      - "01-08-dividers"
      - "01-09-poetry"
      - "01-10-questions"
      - "02-00-images"
      - "02-01-plain-images"
      - "02-02-figures"
      - "03-00-code-and-maths"
      - "03-01-code"
      - "03-02-maths"
      - "04-00-interactivity"
      - "04-01-links-buttons"
      - "04-02-video"
      - "04-03-audio"
      - "04-04-iframes"
      - "04-05-slides"
      - "10-00-indexes"
      - "10-01-traditional-index"
      - "10-02-dynamic-index"
    start-page: "00-05-contents-page" # At which file should users start reading?
    contents-page: "00-05-contents-page" # Your contents-page file, if you have one.
